-- =============================================================================
-- IRD — initial schema
--
-- Three rules shape almost everything below:
--
--  1. The guest must never learn which kitchen cooks a dish. `menu_items`
--     carries `kitchen_id` because the order fan-out depends on it, but the
--     client reads `public_menu`, which does not expose it.
--
--  2. Kitchen and property WhatsApp numbers are not public. `kitchens` and
--     `addresses` are readable only through SECURITY DEFINER functions that
--     return one row for a code you already hold — so nobody can list them.
--
--  3. Money is stored as integer paise. Never floats: 0.1 + 0.2 is a bug
--     waiting to reach an invoice.
-- =============================================================================

-- ----------------------------------------------------------------- addresses
-- One row per QR code: a room in a rest house. `id` is the address_id the
-- operations sheet uses. `public_code` is what the QR actually carries, and it
-- is random precisely so that nobody can walk 1, 2, 3 and harvest every
-- property, room and phone number in the system.
create table if not exists public.addresses (
  id            bigint generated by default as identity primary key,
  public_code   text        not null unique,
  place_name    text        not null,
  room_number   text        not null,
  address       text        not null,
  area          text,
  pin_code      text,
  city          text        not null default 'Vrindavan',
  latitude      numeric(9, 6),
  longitude     numeric(9, 6),
  phone_number  text,
  is_active     boolean     not null default true,
  created_at    timestamptz not null default now()
);
create index if not exists addresses_public_code_idx on public.addresses (public_code);

-- ------------------------------------------------------------------ kitchens
-- Partner kitchens. The WhatsApp number here is what the fan-out messages.
create table if not exists public.kitchens (
  id               uuid primary key default gen_random_uuid(),
  name             text        not null,
  whatsapp_number  text        not null,
  address          text,
  opens_at         time,
  closes_at        time,
  is_active        boolean     not null default true,
  created_at       timestamptz not null default now()
);

-- --------------------------------------------------------- delivery partners
create table if not exists public.delivery_partners (
  id               uuid primary key default gen_random_uuid(),
  name             text        not null,
  whatsapp_number  text        not null,
  is_active        boolean     not null default true,
  created_at       timestamptz not null default now()
);

-- ------------------------------------------------------------------ the menu
create table if not exists public.categories (
  id          uuid primary key default gen_random_uuid(),
  slug        text    not null unique,
  name        text    not null,
  description text,
  sort_order  int     not null default 0,
  is_active   boolean not null default true
);

create table if not exists public.menu_items (
  id            uuid primary key default gen_random_uuid(),
  kitchen_id    uuid    not null references public.kitchens (id),
  category_id   uuid    not null references public.categories (id),
  name          text    not null,
  description   text,
  -- integer paise. 24900 is Rs 249.00
  price_paise   int     not null check (price_paise > 0),
  serves        text,
  image_url     text,
  -- Vrindavan is vegetarian-only, so there is no veg flag: everything is veg.
  -- This is the no-onion-garlic distinction instead.
  is_sattvic    boolean not null default true,
  is_available  boolean not null default true,
  sort_order    int     not null default 0,
  created_at    timestamptz not null default now()
);
create index if not exists menu_items_category_idx on public.menu_items (category_id);
create index if not exists menu_items_kitchen_idx  on public.menu_items (kitchen_id);

-- -------------------------------------------------------------------- orders
do $$ begin
  create type public.order_status as enum (
    'pending_payment', 'paid', 'sent_to_kitchen',
    'preparing', 'out_for_delivery', 'delivered', 'cancelled', 'failed'
  );
exception when duplicate_object then null; end $$;

create table if not exists public.orders (
  id                 uuid primary key default gen_random_uuid(),
  order_no           text        not null unique,
  -- the receipt URL is guessable if it uses order_no, so it uses this instead
  receipt_token      uuid        not null default gen_random_uuid(),
  address_id         bigint      not null references public.addresses (id),
  guest_user_id      uuid        references auth.users (id),
  guest_name         text        not null,
  guest_phone        text        not null,
  guest_email        text,
  status             public.order_status not null default 'pending_payment',
  subtotal_paise     int         not null,
  delivery_paise     int         not null default 0,
  packing_paise      int         not null default 0,
  tax_paise          int         not null default 0,
  total_paise        int         not null,
  note               text,
  razorpay_order_id  text,
  razorpay_payment_id text,
  paid_at            timestamptz,
  created_at         timestamptz not null default now()
);
create index if not exists orders_guest_idx   on public.orders (guest_user_id);
create index if not exists orders_receipt_idx on public.orders (receipt_token);

-- Line items snapshot name, price and kitchen at the time of ordering, so a
-- later menu edit cannot rewrite history or misroute a ticket.
create table if not exists public.order_items (
  id                uuid primary key default gen_random_uuid(),
  order_id          uuid not null references public.orders (id) on delete cascade,
  menu_item_id      uuid references public.menu_items (id),
  kitchen_id        uuid not null references public.kitchens (id),
  name_snapshot     text not null,
  unit_price_paise  int  not null,
  qty               int  not null check (qty > 0),
  line_total_paise  int  not null
);
create index if not exists order_items_order_idx on public.order_items (order_id);

-- One ticket per kitchen per order: this is the unit that gets sent and tracked.
create table if not exists public.order_tickets (
  id          uuid primary key default gen_random_uuid(),
  order_id    uuid not null references public.orders (id) on delete cascade,
  kitchen_id  uuid not null references public.kitchens (id),
  status      text not null default 'pending',
  accepted_at timestamptz,
  ready_at    timestamptz,
  created_at  timestamptz not null default now(),
  unique (order_id, kitchen_id)
);

-- Every WhatsApp send, so a silent failure is visible rather than a guest
-- waiting on food no kitchen ever heard about.
create table if not exists public.message_log (
  id                  uuid primary key default gen_random_uuid(),
  order_id            uuid references public.orders (id) on delete cascade,
  recipient_type      text not null check (recipient_type in ('kitchen','delivery','property')),
  recipient_number    text not null,
  template            text,
  payload             jsonb,
  status              text not null default 'queued',
  provider_message_id text,
  error               text,
  attempts            int  not null default 0,
  created_at          timestamptz not null default now(),
  sent_at             timestamptz
);
create index if not exists message_log_order_idx on public.message_log (order_id);

-- =============================================================================
-- Row level security — deny by default, then open only what must be open.
-- =============================================================================
alter table public.addresses         enable row level security;
alter table public.kitchens          enable row level security;
alter table public.delivery_partners enable row level security;
alter table public.categories        enable row level security;
alter table public.menu_items        enable row level security;
alter table public.orders            enable row level security;
alter table public.order_items       enable row level security;
alter table public.order_tickets     enable row level security;
alter table public.message_log       enable row level security;

-- No policies for addresses, kitchens, delivery_partners, order_items,
-- order_tickets or message_log. They are reachable only via the secret key
-- (edge functions) or the definer functions below.

-- A guest may read their own orders, and nothing else. Writes go through the
-- edge function, which recomputes the price — the client is never trusted with
-- a total, so it gets no insert or update policy at all.
drop policy if exists orders_select_own on public.orders;
create policy orders_select_own on public.orders
  for select to authenticated
  using (guest_user_id = (select auth.uid()));

-- ------------------------------------------------------- the menu, published
-- The base tables stay locked. This view is the only menu the client sees, and
-- it deliberately omits kitchen_id: the guest must not learn that their order
-- is being split. It runs as owner (security_invoker off) so it can read
-- through the RLS above.
create or replace view public.public_menu
with (security_invoker = false) as
  select m.id,
         m.category_id,
         c.slug  as category_slug,
         c.name  as category_name,
         m.name,
         m.description,
         m.price_paise,
         m.serves,
         m.image_url,
         m.is_sattvic,
         m.sort_order,
         c.sort_order as category_sort_order
    from public.menu_items m
    join public.categories c on c.id = m.category_id
   where m.is_available
     and c.is_active;

grant select on public.public_menu to anon, authenticated;

-- ---------------------------------------------------- resolving a QR address
-- Takes a code the caller already has and returns that one row. Because the
-- table itself is unreadable, there is no way to list or enumerate addresses,
-- and the property's phone number is never returned to the browser.
create or replace function public.resolve_address(p_code text)
returns table (
  address_id  bigint,
  place_name  text,
  room_number text,
  address     text,
  area        text,
  city        text,
  pin_code    text
)
language sql
security definer
set search_path = public
stable
as $$
  select a.id, a.place_name, a.room_number, a.address, a.area, a.city, a.pin_code
    from public.addresses a
   where a.public_code = p_code
     and a.is_active
   limit 1;
$$;

revoke all on function public.resolve_address(text) from public;
grant execute on function public.resolve_address(text) to anon, authenticated;

-- ------------------------------------------------------- fetching a receipt
-- Same shape: the token is unguessable, so holding it is the authorisation.
create or replace function public.get_receipt(p_token uuid)
returns jsonb
language sql
security definer
set search_path = public
stable
as $$
  select jsonb_build_object(
    'order_no',   o.order_no,
    'created_at', o.created_at,
    'status',     o.status,
    'place_name', a.place_name,
    'room_number', a.room_number,
    'guest_name', o.guest_name,
    'subtotal_paise', o.subtotal_paise,
    'delivery_paise', o.delivery_paise,
    'packing_paise',  o.packing_paise,
    'tax_paise',      o.tax_paise,
    'total_paise',    o.total_paise,
    'items', (
      select coalesce(jsonb_agg(jsonb_build_object(
               'name', i.name_snapshot,
               'qty',  i.qty,
               'unit_price_paise', i.unit_price_paise,
               'line_total_paise', i.line_total_paise
             ) order by i.name_snapshot), '[]'::jsonb)
        from public.order_items i where i.order_id = o.id
    )
  )
  from public.orders o
  join public.addresses a on a.id = o.address_id
  where o.receipt_token = p_token;
$$;

revoke all on function public.get_receipt(uuid) from public;
grant execute on function public.get_receipt(uuid) to anon, authenticated;
